Referir_Paga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework import routers
from apps.apisReferirPagaApp import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from myapp.views import UserViewSet

# Apis
from apps.usuarios.forms import PasswordResetForm2

router = routers.SimpleRouter()
router.register(r'loginApp', views.LoginSerializer, basename='loginApp'),
router.register(r'usuarioApp', views.UsuarioSerializer, basename='usuarioApp'),
router.register(r'usuarioReg', views.UsuarioUpdateSerializer, basename='usuarioReg'),
router.register(r'pais', views.PaisSerializer),
router.register(r'ciudad', views.CiudadSerializer),
router.register(r'documento', views.DocumentoSerializer, basename='documento'),
router.register(r'listaEmpresa', views.ClienteEmpresa, basename='listaEmpresa'),
router.register(r'empresa', views.EmpresaCliente, basename='empresa'),
router.register(r'codigo', views.CodigoSerializer, basename='codigo'),
router.register(r'validaCodigo', views.ValidacionCodigo, basename='validaCodigo'),
router.register(r'servicio', views.ServiciosSerializer, basename='servicio'),
router.register(r'enlace', views.EnlacesClienteSerializer, basename='enlace'),
router.register(r'lisUsuario', views.ListarUsuario, basename='lisUsuario'),
router.register(r'referir', views.ReferidoAppSerializer, basename='referir'),

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('', include('apps.recursos.urls')),
                  path('loggin/', include('apps.logginas.urls', namespace="logginas"),),
                  path('cliente/', include('apps.clientes.urls', namespace="clientes"), ),
                  path('usuario/', include('apps.usuarios.urls', namespace="usuarios"), ),
                  path('sede/', include('apps.sedes.urls', namespace="sedes"), ),
                  path('services/', include('apps.services.urls', namespace="services"), ),
                  path('gestores/', include('apps.gestores.urls', namespace="gestores"), ),
                  path('reportes/', include('apps.reportes.urls', namespace="reportes"), ),
                  path('password_reset/', auth_views.PasswordResetView.as_view(template_name='otros/send_email.html',
                                                                               html_email_template_name='otros/template_email.html',
                                                                               form_class=PasswordResetForm2),
                       name="password_reset"),
                  path('password_reset/done/',
                       auth_views.PasswordResetDoneView.as_view(template_name='otros/password_reset_done.html'),
                       name="password_reset_done"),
                  path('reset/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(template_name="otros/password_reset_confirm.html"),
                       name="password_reset_confirm"),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(template_name="otros/password_reset_complete.html"),
                       name="password_reset_complete"),

                  # APis
                  path('', include(router.urls)),
                  path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                  # TareasProgramadas
                  path('tarea/', include('apps.tareasProgramadas.urls', namespace="tareaPro"), )


              ]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/gestores/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *

app_name = "gestores"
urlpatterns = [
    path('nuevo-servicio/',CrearServicio.as_view(), name="servicio-nuevo"),
    path('listar-servicio/',ListarServicio.as_view(), name="servicio-index"),
    path('actualizar-servicio/<int:pk>/',ActualizarServicio.as_view(), name="servicio-actualizar"),
    path('consultar-servicio/<int:pk>/<str:delete>/',ConsultaServicio.as_view(), name="servicio-consultar"),
    path('eliminar-servicio/',EliminarServicio.as_view(), name="servicio-eliminar"),

    path('nuevo-producto/',CrearProducto.as_view(), name="producto-nuevo"),
    path('listar-producto/',ListarProducto.as_view(), name="producto-index"),
    path('subir-producto/',views.product_upload, name="producto-upload"),
    path('actualizar-producto/<int:pk>/',ActualizarProducto.as_view(), name="producto-actualizar"),
    path('consultar-producto/<int:pk>/<str:delete>/',ConsultarProducto.as_view(), name="producto-consultar"),
    path('eliminar-producto/',EliminarProducto.as_view(), name="producto-eliminar"),
    path('productos/<str:filepath>/', views.download_file, name="producto-formato"),

    path('nuevo-publicidad/',CrearPublicidad.as_view(), name="publicidad-nuevo"),
    path('listar-publicidad/',ListarPublicidad.as_view(), name="publicidad-index"),
    path('actualizar-publicidad/<int:pk>/',ActualizarPublicidad.as_view(), name="publicidad-actualizar"),
    path('consultar-publicidad/<int:pk>/<str:delete>/',ConsultaPublicidad.as_view(), name="publicidad-consultar"),
    path('eliminar-publicidad/',EliminarPublicidad.as_view(), name="publicidad-eliminar"),

    path('nuevo-enlace/',CrearEnlace.as_view(), name="enlace-nuevo"),
    path('listar-enlace/',ListarEnlace.as_view(), name="enlace-index"),
    path('actualizar-enlace/<int:pk>/',ActualizarEnlace.as_view(), name="enlace-actualizar"),
    path('consultar-enlace/<int:pk>/<str:delete>/',ConsultaEnlace.as_view(), name="enlace-consultar"),
    path('eliminar-enlace/',EliminarEnlace.as_view(), name="enlace-eliminar"),
    
    path('cumpleaños/', Cumpleanhos.as_view(),  name="cumpleanhos"),
    path('cumpleaños/<int:user_id>/', views.birth_mail, name="birth-mail"),
    #Campania
    path('nuevo-campania/',CrearCampania.as_view(), name="campania-nuevo"),
    path('listar-campania/',ListarCampania.as_view(), name="campania-index"),
    path('actualizar-campania/<int:pk>/',ActualizarCampana.as_view(), name="campania-actualizar"),
    path('eliminar-campania/',EliminarCampana.as_view(), name="campania-eliminar"),
    path('consultar-campania/<int:pk>/<str:delete>/',ConsultarCampana.as_view(), name="campania-consultar"),

]

apps/reportes/urls.py
from django.urls import path, include
from . import views


app_name="reportes"
urlpatterns = [
    path('clientes/',views.ReportesClientes, name="reportes-clientes"),
    path('usuarios/',views.ReportesUsuarios, name="reportes-usuarios"),
    path('regionales-pto/',views.ReportesRegionalesPto, name="reportes-regionales-pto"),
    path('enlace/',views.ReportesEnlaces, name="reportes-enlace"),
    path('publicidad/',views.ReportesPublicidades, name="reportes-publicidad"),
    path('servicio/',views.ReportesServicios, name="reportes-servicio"),
    path('campana/',views.ReportesCampana, name="reportes-campana"),
    path('a/',views.A, name="a"),

]

apps/sedes/models.py
from django.db import models
from django.conf import settings
from apps.clientes.models import *
from apps.ubicacion.models import *
from apps.usuarios.models import TIPOS_VIA, PREFIJO_VIA, PUNTO_CARDINAL


class Regional(models.Model):
	estado = models.BooleanField(default=True)
	regional = models.CharField(max_length=250,blank=True)
	cliente = models.ForeignKey(Cliente,on_delete=models.SET_NULL, null=True)#De 1 a *
	descripcion = models.TextField(null=True)
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	fecha_actualizacion = models.DateTimeField(auto_now=True)

	def __str__(self):
		return '{0}'.format((self.regional).upper())

	class Meta():
		verbose_name_plural = "Regionales"


class PtoOperacion(models.Model):
	cliente = models.ForeignKey(Cliente,on_delete=models.SET_NULL, null=True)
	estado = models.BooleanField(default=True)
	nombre = models.CharField(max_length=250)
	regional = models.ForeignKey(Regional, on_delete=models.SET_NULL, null=True)#ForeignKey 1 a m
	imagen = models.ImageField(upload_to = 'imagen-ptoperacion/', default = 'imagen-cliente/user2.svg', null=True, blank=True)
	telefono1 = models.CharField(max_length=10, null=True , blank=True, )
	extencion1 = models.CharField(max_length=6, null=True , blank=True, )
	telefono2 = models.CharField(max_length=10, null=True , blank=True, )
	extencion2 = models.CharField(max_length=6, null=True , blank=True, )
	numero_via = models.IntegerField( null=True , blank=True)
	tipo_via = models.CharField(max_length=12, null=True , blank=True, choices=TIPOS_VIA,)
	prefijo_via = models.CharField(max_length=12, null=True , blank=True, choices=PREFIJO_VIA,)
	bis_via = models.BooleanField(default=False, blank=True)
	cuadrante_via = models.CharField(max_length=12, null=True , blank=True, choices=PUNTO_CARDINAL,)
	numero_via_generadora = models.IntegerField( null=True , blank=True)
	prefijo_via_generadora = models.CharField(max_length=12, null=True , blank=True, choices=PREFIJO_VIA,)
	bis_via_generadora = models.BooleanField(default=False, blank=True)
	numero_placa = models.CharField(max_length=4, null=True , blank=True)
	cuadrante_via_generadora = models.CharField(max_length=12, null=True , blank=True, choices=PUNTO_CARDINAL,)
	complemento = models.CharField(max_length=512, null=True , blank=True,)
	barrio = models.CharField(max_length=512, null=True , blank=True,)
	pais = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True,blank=True) 
	departamento = models.ForeignKey(Departamento, on_delete=models.SET_NULL, null=True, blank=True) 
	ciudad = models.ForeignKey(Ciudad, on_delete=models.SET_NULL, null=True, blank=True) 
	usuarios = models.ManyToManyField(settings.AUTH_USER_MODEL)
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	fecha_actualizacion = models.DateTimeField(auto_now=True)

	def __str__(self):
		nombre=(self.nombre).upper()
		return '{0}'.format(nombre)   

	class Meta():
		verbose_name_plural = "PtoOperaciones"

templates/campania/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block styles %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet"/>
    <link href="{% static 'css/usuarios/index.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
<div class="panel-body"> <!-- end panel Body-->
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'gestores:campania-nuevo' %}" id="new" class="btn btn-success"><i class="fa fa-plus"></i> Nueva Campaña</a>
        </div>
        <div class="col-md-12">
            <div class="contentBuscar">
                <div class="divBuscar">
                    <form id="Idform" method="get">
                        <div id="divInputBuscar" style="float: right;">
                            <button type="submit" style="float: left;" id="btnBuscar" class="btn btn-info">
                                <i class="fa fa-search"></i>Buscar
                            </button>

                            <input type="text" style="width: 188px;" id="buscarCliente" class="form-control" name="q" placeholder="Buscar Campañia" value="{{request.GET.q}}">
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            {% if object_list%}
            {% if page_obj %}
            <strong>
                <p>{{ page_obj.start_index }} - {{ page_obj.end_index }} de {{ page_obj.paginator.count }} resultados
                    <a href="{% url 'reportes:reportes-campana' %}" class="fa fa-file-download iconDescarga">
                    </a>
                </p>
            </strong>
            {% endif %}

            <div class="table-responsive">
                <table class="table responsive" class="table table-striped" id="sort">
                    <thead>
                        <th colspan="12" id="colspan">Listado de Campania</th>
                        <tr>
                            <th class="thAccion">Acción</th>
                            <th>Estado</th>
<!--                            <th>Codigo Campaña</th>-->
                            <th>Nombre<i class="fa fa-fw fa-sort"></i></th>
                            <th>Descripcion</th>
                            <th>Responsable</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in object_list %}
                        <tr>
                            <td class="fitwidth">
                                <a href="{% url 'gestores:campania-consultar' pk=obj.id delete=obj.id %}" title="Consultar" id="Consultar"><span class="fa fa-eye" style="font-size: 15px;" data-toggle="modal" data-target="#exampleModal"></span></a>
                                |
                                {% if not request.user.is_super_administrador %}
                                    <a href="{% url 'gestores:campania-actualizar' pk=obj.id %}" title="Editar" id="editar"><i class="fas fa-pencil-alt"></i></a>
                                {% else %}
                                    <a title="desabilitado" id="editar"><i class="fas fa-pencil-alt"></i></a>
                                {% endif %}
                                | 
                                <a href="{% url 'gestores:campania-consultar' pk=obj.id delete='Eliminar' %}" title="Eliminar" id="eliminar"><span class="glyphicon glyphicon-trash" data-toggle="modal" data-target="#exampleModal"></span></a>
                            </td>
                            <td>
                                {% if obj.estado %}
                                    <span class="label label-success">Activo</span>
                                {%else%}
                                    <span class="label label-danger">Inactivo</span>
                                {% endif %}
                            </td>
<!--                           <td>{{obj.codigoCampana |default_if_none:"Sin Codigo" |upper}}</td> -->
                           <td>{{obj.nombre |default_if_none:"Sin Dato" |upper}}</td>
                           <td style="width: 40%;">{{obj.descripcion |default_if_none:"Sin Dato" |upper}}</td> 
                           <td>{{obj.responsableCampana |default_if_none:"Sin Responsable" |upper}}</td> 
                           <td>{{obj.fecha_inicio |upper}}</td> 
                           <td id="columnFechaF" value="{{obj.fecha_fin|upper}}">{{obj.fecha_fin|upper}}</td> 
                        </tr>
                            {% endfor %}
                    </tbody> 
                </table>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
                <script>
                $(document).ready(function() {
                   $("#sort").DataTable({
                         "searching": false,
                         "ordering": true,
                         "paging": false,
                         "info": false,
                         columnDefs : [
                             { type : 'Nombre', targets : [3] }
                             ],
                                });
                                });
                </script>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="waves-effect"><a href="?page=
                        {{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
                            <i class="fa fa-angle-left"></i>
                        </a>
                    </li>
                    {% else %}
                    <li class="disabled"><a href="#!"><i class="fa fa-angle-left"></i></a></li>
                    {% endif %}
                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="active"><a href="#!">{{ num }}</a></li>
                            {% else %}
                                <li class="waves-effect"><a href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}
                    {% if page_obj.has_next %}

                    <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>

                    {% else %}
                        <li class="disabled"><a href="#!"> <i class="fa fa-angle-right"></i></a></li>
                    {% endif %}
                </ul>
            </div>
            {%else%}
            <input type="hidden" name="q" value="0" id="inputSinRegistros">
            <div style="text-align:center; margin-top:6%;">
                <i class="fa fa-database" style="font-size: 94px;"></i>
                <span style="font-size: 44px;">&nbsp; Sin Registros</span>
            </div>
            {%endif%}
            <p id="empty_set" hidden>{{ empty_set }}</p>
        </div>
    </div>
</div> <!-- end panel Body-->
{% endblock %}

{% block scripts %}

<script type="text/javascript">
    $("tr:odd").css("background-color", "#daf4ff");
</script>
<script>
    var registros;
    registros = $("#inputSinRegistros").val();
    var empty_set = $("#empty_set").text();
    if ( empty_set == 1){
        if (registros == 0) {
            Swal.fire({
                title: '¡Sin Datos!',
                text: "No Cuenta Con Resgistros Relacionados Con La Búsqueda",
                type: 'warning',
                confirmButtonColor: '#3085d6',
                confirmButtonText: 'Aceptar'
            }).then((result) => {
                if (result.value) {
                    registros = 1;
                    var url = "{% url 'gestores:campania-index' %}";
                    window.location.href = url;
                }
            });
        }
    }

</script>

{% endblock %}

templates/campania/nuevo.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block styles %}
     <link href="{% static 'css/regional/nuevo.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}

<div class="content">
    <div class="row">
        <form method="post" enctype="multipart/form-data" id="form">{% csrf_token %}
            <a href='{% url "gestores:campania-index" %}' class="btn btn-success">
                <i class="fa fa-angle-left"></i>Gestor de Campañas
            </a> 

            <div class="content"><!--formulario-->
                <div class="row">
                    {% if 'actualizar' in request.path %}
                        <div class="col-md-12">
                            <!--Edita Informacion-->
                            <input type="hidden" value="editar" name="editarInfo" id="editarInfo">
                            <!--Edita Informacion-->
                          
                            <div class="panel-heading ui-draggable-handle">
                                <h3 class="panel-title">
                                    <strong id="actualizaCam">Actualizar Campaña</strong>
                                </h3>
                            </div>
                            
                            <div class="container">
                              <div class="col-md-10">
                                <!--Estado-->
                                <div class="onoffswitch">
                                    <input type="checkbox" disabled name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
                                     <label class="onoffswitch-label" for="myonoffswitch">
                                        <span class="onoffswitch-inner" value="0"></span>
                                        <span class="onoffswitch-switch spanInActivo" value="1"></span>
                                    </label>
                                </div>
                                <!--Estado-->
                              </div>
                            </div>
                        </div>
                        
                    {% else %}
                    <div class="col-md-12">
                        <div class="panel-heading ui-draggable-handle">
                            <h3 class="panel-title">
                                 <strong id="actualizaCam">Nueva Campaña</strong>
                            </h3>
                        </div>
                  
                        <div class="row">
                            <div class="contentEstado">
                                <!--Estado-->
                                <div class="onoffswitch">
                                    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked disabled> 
                                     <label class="onoffswitch-label" for="myonoffswitch">
                                        <span class="onoffswitch-inner span" value="0"></span>
                                        <span class="onoffswitch-switch span" value="1"></span>
                                    </label>
                                </div>
                                <!--Estado-->
                            </div>
                        </div>
                    </div>

                </div>
                    {% endif %}
            </div>
            </br>
            </br>

            <div class="col-md-9" style="display: none;">
                {{form.estado}} 
                <strong class="help-block"></strong>
            </div>
        <div class="row">
            <div class="col-lg-8 col-md-6 col-sm-6 col-xs-6 divForm">
                <div class="form-group" style="white-space: nowrap;">
                    <label class="col-lg-3 col-md-6 control-label">
                        <i class="far fa-newspaper"></i>&nbsp;&nbsp;Nombre Campañia
                        <strong class="span"> *</strong>
                    </label>
                    <div class="col-lg-9 col-md-6">
                        {{form.nombre}}
                        <strong class="help-block"></strong>
                    </div>
                </div>
                <div class="form-group divAsesor " style="white-space: nowrap;" id="divAsesores">
                    <label class="col-lg-3 col-md-6 control-label">
                    <i class="fas fa-user-tie"></i>&nbsp;&nbsp;Responsable Campaña
                        <strong class="span"> *</strong>
                    </label>
                    <div class="col-lg-9 col-md-6">
                        {{form.responsableCampana}}
                        <span class="help-block"></span>
                    </div>
                </div>
<!--                <div class="form-group divAsesor" id="divAsesores">-->
<!--                    <label class="col-md-4 control-label">-->
<!--                    <i class="fas fa-user-tie"></i>&nbsp;&nbsp;Asesor</label>-->
<!--                    <div class="col-md-8">-->
<!--                        {{form.asesor}}-->
<!--                        <span class="help-block"></span>-->
<!--                    </div>-->
<!--                </div>-->
                <div class="form-group">
                    <label class="col-lg-3 col-md-6 control-label">
                        <i class="fas fa-link"></i>&nbsp;&nbsp;fecha Inicio
                        <strong class="span"> *</strong>
                    </label>
                    <div class="col-lg-9 col-md-6">
                        {{form.fecha_inicio}}
                        <strong class="help-block"></strong>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 col-md-6 control-label">
                        <i class="fas fa-link"></i>&nbsp;&nbsp;fecha Fin
                        <strong class="span"> *</strong>
                    </label>
                    <div class="col-lg-9 col-md-6">
                        {{form.fecha_fin}}
                        <strong class="help-block"></strong>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 col-md-6 control-label">
                        <i class="fas fa-link"></i>&nbsp;&nbsp;Descripcion
                        <strong class="span"> *</strong>
                    </label>
                    <div class="col-lg-9 col-md-6">
                        {{form.descripcion}}
                        <strong class="help-block"></strong>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 divForm"></div>
         </div>
            <div>
                {% if 'actualizar' in request.path %}
                    <button type="submit" id="btnGuardar" class="btn btn-primary pull-right">
                        <i class="fa fa-save" aria-hidden="true"></i>Actualizar
                    </button>
                {% else %}
                    {% if not request.user.is_super_administrador %}
                        <button type="submit" id="btnGuardar" class="btn btn-primary pull-right">
                            <i class="fa fa-save" aria-hidden="true"></i>Guardar
                        </button>
                    {% endif %}
                {% endif %}
                <button type="button" class="btn btn-danger pull-right"  id="btnLimpiar">
                    <i class="fa fa-trash-o" aria-hidden="true"></i>Limpiar
                </button> 
            </div> 
        </form>
     </div>
</div>

{% endblock %}

{% block scripts %}
<script>
notificaciones();
//Estado Actual
var estado = $("#id_estado").is(':checked');
if( estado ){
    $("#myonoffswitch").attr('checked',true);
}else{
    $("#myonoffswitch").attr('checked',false);
}
//New Estado
$("#myonoffswitch").change(function() {
    if ($(this).prop('checked') == true ) {
        $("#id_estado").prop('checked',true);
    }else {
        $("#id_estado").attr('checked',false);
    }
});

document.getElementById("btnLimpiar").addEventListener('click',() =>{
    var dato = $("#actualizaCam").text();
    if( dato != "Actualizar Campaña" ){
        $("#id_nombre").val("")
    }
    $("#id_descripcion").val("")
    $("#id_fecha_inicio").val("")
    $("#id_fecha_fin").val("")
    $("#id_responsableCampana").val("")
});

document.getElementById("btnGuardar").addEventListener('click',() =>{
    var name = document.getElementById("id_nombre").value;
    var descrip = document.getElementById("id_descripcion").value;
    var fechI = document.getElementById("id_fecha_inicio").value;
    var fechF = document.getElementById("id_fecha_fin").value;
    var valor = $("#id_responsableCampana option:selected").val();
    var guardar = "crear"
    if( dato != "Actualizar Campaña" ){
        var guardar = "actualizar"
    }
    if ( (name != '') && (descrip != '') && ( fechI != '' ) && ( fechF != '' ) && ( valor != '' ) ){
        event.preventDefault();
            Swal.fire({
              title: 'Atención',
              text: `Esta seguro que desea ${guardar} este registro?`,
              type: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#d33',
              confirmButtonText: 'Si, confirmar'
            }).then((result) => {
                if (result.value) {
                    $("#form").submit();
                    Swal.fire({
                      title: 'Felicidades',
                      text: "Campañia Guardada Exitosamente",
                      type: 'success',
                      confirmButtonColor: '#3085d6',
                      confirmButtonText: 'Aceptar'
                    }).then((result) => {
                        var url = "{% url 'gestores:campania-index' %}";
                        window.location.href = url;
                    });
                }
            });
    }
});

//Campo Fecha
var d = new Date();
var dia = d.getDate();
var diaActual = '0'+dia;
var mes = d.getMonth()+1;
var m = '0'+ mes.toString();
//Validaciones Fecha
var diaHoy = dia <= 9 ? diaActual : dia;
var mesHoy = mes <= 9 ? m : mes;
var fecha = d.getFullYear()+"-"+mesHoy+'-'+diaHoy;
console.log('edito '+fecha)
$("#id_fecha_inicio").attr('min',fecha);


document.getElementById("id_fecha_inicio").addEventListener('change',() =>{
    fechaInicio = $("#id_fecha_inicio").val();
    $("#id_fecha_fin").attr('min',fechaInicio);
    $("#id_descripcion").focus();
});

document.getElementById("id_fecha_fin").addEventListener('change',() =>{
    $("#id_descripcion").focus();
});

//Vista Actualizar
var dato = $("#actualizaCam").text();
if( dato == "Actualizar Campaña" ){
  var fi = $(".fechaInicio").attr('value');
  var ff = $("#id_fecha_fin").attr('value');

  $(".fechaInicio").val( fi.split("/").reverse().join("-") );
  $("#id_fecha_fin").val( ff.split("/").reverse().join("-") );

   var dato = $("#id_fecha_inicio").val();
   $("#id_fecha_fin").attr('min',dato);
}
</script>



{% if messages %}
    {% for message in messages %}
    {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
        <script >
            notificaciones('{{message|escape}}');
        </script>
    {% endfor %}
{% endif %}


{% if form.errors %}
    {% for field in form %}
        {% if field.errors %}
            {% for error in field.errors %}
                <script>
                    notificaciones("{{ error|escape }}");
                    $("#id_pais").prop('selectedIndex',0).change();
                </script>
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endif %}

{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <script>
            notificaciones("{{ error|escape }}");
        </script>
    {% endfor %}
{% endif %}


<!--Nelson-->
{% endblock %}