Referir_Paga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework import routers
from apps.apisReferirPagaApp import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from myapp.views import UserViewSet

# Apis
from apps.usuarios.forms import PasswordResetForm2

router = routers.SimpleRouter()
router.register(r'loginApp', views.LoginSerializer, basename='loginApp'),
router.register(r'usuarioApp', views.UsuarioSerializer, basename='usuarioApp'),
router.register(r'usuarioReg', views.UsuarioUpdateSerializer, basename='usuarioReg'),
router.register(r'pais', views.PaisSerializer),
router.register(r'ciudad', views.CiudadSerializer),
router.register(r'documento', views.DocumentoSerializer, basename='documento'),
router.register(r'listaEmpresa', views.ClienteEmpresa, basename='listaEmpresa'),
router.register(r'empresa', views.EmpresaCliente, basename='empresa'),
router.register(r'codigo', views.CodigoSerializer, basename='codigo'),
router.register(r'validaCodigo', views.ValidacionCodigo, basename='validaCodigo'),
router.register(r'servicio', views.ServiciosSerializer, basename='servicio'),
router.register(r'enlace', views.EnlacesClienteSerializer, basename='enlace'),
router.register(r'lisUsuario', views.ListarUsuario, basename='lisUsuario'),
router.register(r'referir', views.ReferidoAppSerializer, basename='referir'),

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('', include('apps.recursos.urls')),
                  path('loggin/', include('apps.logginas.urls', namespace="logginas"),),
                  path('cliente/', include('apps.clientes.urls', namespace="clientes"), ),
                  path('usuario/', include('apps.usuarios.urls', namespace="usuarios"), ),
                  path('sede/', include('apps.sedes.urls', namespace="sedes"), ),
                  path('services/', include('apps.services.urls', namespace="services"), ),
                  path('gestores/', include('apps.gestores.urls', namespace="gestores"), ),
                  path('reportes/', include('apps.reportes.urls', namespace="reportes"), ),
                  path('password_reset/', auth_views.PasswordResetView.as_view(template_name='otros/send_email.html',
                                                                               html_email_template_name='otros/template_email.html',
                                                                               form_class=PasswordResetForm2),
                       name="password_reset"),
                  path('password_reset/done/',
                       auth_views.PasswordResetDoneView.as_view(template_name='otros/password_reset_done.html'),
                       name="password_reset_done"),
                  path('reset/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(template_name="otros/password_reset_confirm.html"),
                       name="password_reset_confirm"),
                  path('reset/done/',
                       auth_views.PasswordResetCompleteView.as_view(template_name="otros/password_reset_complete.html"),
                       name="password_reset_complete"),

                  # APis
                  path('', include(router.urls)),
                  path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                  # TareasProgramadas
                  path('tarea/', include('apps.tareasProgramadas.urls', namespace="tareaPro"), )


              ]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clientes/urls.py
from django.urls import path, include
from . import views

app_name = "clientes"
urlpatterns = [
    path('', views.ListarClientes.as_view(), name="cliente-index"),
    # path('eliminar/<int:pk>/',views.EliminarClientes, name="cliente-eliminar"),
    path('delete-cliente', views.DeleteCliente.as_view(), name="cliente-delete"),
    path('desactivar/<int:pk>/', views.DesactivarClientes, name="cliente-desactivar"),
    path('activar/<int:pk>/', views.ActivarClientes, name="cliente-activar"),
    path('nuevo/', views.CrearCliente.as_view(), name="cliente-nuevo"),
    path('actualizar/<int:pk>/', views.ActualizarCliente, name="cliente-actualizar"),
    path('get-identificacion/', views.identificacion, name="get-identificacion"),
    path('get-departamento/', views.departamento, name="get-departamento"),
    path('get-ciudad/', views.ciudad, name="get-ciudad"),
    path('consultar/<int:pk>/<str:delete>/', views.ConsultaCliente.as_view(), name="cliente-consultar"),
]

apps/gestores/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *

app_name = "gestores"
urlpatterns = [
    path('nuevo-servicio/',CrearServicio.as_view(), name="servicio-nuevo"),
    path('listar-servicio/',ListarServicio.as_view(), name="servicio-index"),
    path('actualizar-servicio/<int:pk>/',ActualizarServicio.as_view(), name="servicio-actualizar"),
    path('consultar-servicio/<int:pk>/<str:delete>/',ConsultaServicio.as_view(), name="servicio-consultar"),
    path('eliminar-servicio/',EliminarServicio.as_view(), name="servicio-eliminar"),

    path('nuevo-producto/',CrearProducto.as_view(), name="producto-nuevo"),
    path('listar-producto/',ListarProducto.as_view(), name="producto-index"),
    path('subir-producto/',views.product_upload, name="producto-upload"),
    path('actualizar-producto/<int:pk>/',ActualizarProducto.as_view(), name="producto-actualizar"),
    path('consultar-producto/<int:pk>/<str:delete>/',ConsultarProducto.as_view(), name="producto-consultar"),
    path('eliminar-producto/',EliminarProducto.as_view(), name="producto-eliminar"),
    path('productos/<str:filepath>/', views.download_file, name="producto-formato"),

    path('nuevo-publicidad/',CrearPublicidad.as_view(), name="publicidad-nuevo"),
    path('listar-publicidad/',ListarPublicidad.as_view(), name="publicidad-index"),
    path('actualizar-publicidad/<int:pk>/',ActualizarPublicidad.as_view(), name="publicidad-actualizar"),
    path('consultar-publicidad/<int:pk>/<str:delete>/',ConsultaPublicidad.as_view(), name="publicidad-consultar"),
    path('eliminar-publicidad/',EliminarPublicidad.as_view(), name="publicidad-eliminar"),

    path('nuevo-enlace/',CrearEnlace.as_view(), name="enlace-nuevo"),
    path('listar-enlace/',ListarEnlace.as_view(), name="enlace-index"),
    path('actualizar-enlace/<int:pk>/',ActualizarEnlace.as_view(), name="enlace-actualizar"),
    path('consultar-enlace/<int:pk>/<str:delete>/',ConsultaEnlace.as_view(), name="enlace-consultar"),
    path('eliminar-enlace/',EliminarEnlace.as_view(), name="enlace-eliminar"),
    
    path('cumpleaños/', Cumpleanhos.as_view(),  name="cumpleanhos"),
    path('cumpleaños/<int:user_id>/', views.birth_mail, name="birth-mail"),
    #Campania
    path('nuevo-campania/',CrearCampania.as_view(), name="campania-nuevo"),
    path('listar-campania/',ListarCampania.as_view(), name="campania-index"),
    path('actualizar-campania/<int:pk>/',ActualizarCampana.as_view(), name="campania-actualizar"),
    path('eliminar-campania/',EliminarCampana.as_view(), name="campania-eliminar"),
    path('consultar-campania/<int:pk>/<str:delete>/',ConsultarCampana.as_view(), name="campania-consultar"),

]

apps/logginas/urls.py
from django.urls import path
from . import views

app_name = 'logginas'

urlpatterns = [
    path('select/<int:usuario_id>/', views.select_view, name='select-user'),
    path('reset/', views.reset_view, name='reset-user'),
]

apps/sedes/urls.py
from django.urls import path, include
from apps.sedes import views

app_name="sedes"
urlpatterns = [
	path('get_pto/',views.Get_pto, name="pto-get"),
	path('',views.ListarRegional.as_view(), name="regional-index"),
	path('nuevo/',views.CrearRegional.as_view(), name="regional-nuevo"),
    path('actualizar/<int:pk>/',views.ActualizarRegional, name="regional-actualizar"),
    path('consultar/<int:pk>/<str:delete>/',views.ConsultaRegional.as_view(),name="regional-consultar"),
    path('eliminar/',views.EliminarRegional.as_view(), name="regional-eliminar"),
    #PtOperacion
    path('nuevo-pto/',views.CrearPuntoOperacion.as_view(), name="pto-nuevo"),
    path('listar-pto/',views.ListarPuntoOperacion.as_view(), name="pto-index"),
    path('actualizar-pto/<int:pk>/',views.ActualizarPuntoOperacion.as_view(), name="pto-actualizar"),
    path('consultar-pto/<int:pk>/<str:delete>/',views.ConsultaPto.as_view(),name="pto-consultar"),
    path('eliminar-pto/',views.EliminarPto.as_view(), name="pto-eliminar"),
]

templates/bootstrap_datetimepicker.html
<div class="input-group date" id="{{ widget.datetimepicker_id }}" data-target-input="nearest">
  {% include "django/forms/widgets/input.html" %}
  <div class="input-group-append" data-target="#{{ widget.datetimepicker_id }}" data-toggle="datetimepicker">
    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
  </div>
</div>

<script>
  $(function () {
    $("#{{ widget.datetimepicker_id }}").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>

templates/confirmar_activacion.html
{% extends 'base.html' %}
{% load i18n %}

{% load static %}
{% block styles %}

{% endblock %}

{% block content %}
<dic class="row" style="display:none;">
	
</style>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to activate "{{ object }}"?</p>
    <input type="submit" value="Confirm" id="confirm">
</form>
</dic>
{% endblock %}

{% block scripts %}

<script>

		Swal.fire({
			  title: 'Atención ..?',
			  text: "Desea Activar El Registro {{ object }} ..?",
			  type: 'warning',
			  showCancelButton: true,
			  confirmButtonColor: '#3085d6',
			  cancelButtonColor: '#d33',
			  confirmButtonText: 'Si, Activar'
		}).then((result) => {
		  if (result.value) {
		    Swal.fire(
		      	'Felicidades ...',
		      	'Activado Exitosamente',
		      	'success',
		    )
   			function explode(){
				$("#confirm").click();
			}
			setTimeout(explode, 1500);

		  }else{
		  	window.location.href="{% url 'clientes:cliente-index' %}"
		  }

		});


</script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load i18n %}


{% load static %}
{% block styles %}

{% endblock %}

{% block content %}
{{user.last_login}}

{% endblock %}

{% block scripts %}
{% endblock %}

templates/login.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en" class="body-full-height">

<head>

    <!-- META SECTION -->
    <title>Login</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{% static 'img/favicon.svg' %}" type="image/x-icon" />
    <link href="{% static 'css/fontawesome-free-5.10.0-11/css/all.css' %}" rel='stylesheet'/>
    <!-- END META SECTION -->
    <!-- CSS INCLUDE -->
    <link rel="stylesheet" type="text/css" id="theme" href="{% static 'css/theme-default.css' %}" />

    <!-- EOF CSS INCLUDE -->
</head>

<body>
    <div class="login-container lightmode">
        <div class="login-box animated fadeInDown">
            <div class="login-logo"></div>
            <div class="login-body">
                <div class="login-title" style="text-align:center;"><strong>Ingresa a tu cuenta</div>

                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-12"> {{ form.username.label_tag }}</div>
                            <div class="col-md-12">{{ form.username }}</div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">{{ form.password.label_tag }}</div>
                            <div class="col-md-12">{{ form.password }}</div>
                        </div>
                    <p class="text-right"><a href="{% url 'password_reset'%}" class="btn btn-link" style="color:#0074D9;">¿Olvidaste tu contraseña?</a></p>
                        <div>
                            <button class="btn btn-block" style="background-color:#ff5e5e;color: white; font-size: 1.2em; font-weight: 100; border-radius:10px;">Ir</button>
                        </div>
                    <input type="hidden" name="next" value="{{ next }}">
                </form>
            </div>
            <div class="login-footer">
                <div class="pull-left">
                    &copy; 2019 Referir Paga
                </div>
                <div class="pull-right">
                </div>
            </div>
        </div>

    </div>

</body>

<script type="text/javascript" src="{% static 'js/plugins/jquery/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/jquery/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/bootstrap/bootstrap.min.js' %}"></script>



<script type="text/javascript" src="{% static 'js/plugins/sweetalert2.8/sweetalert.js' %}"></script>

<script>
    $("input").addClass("form-control")
</script>


{% if form.errors %}
    <script>
        console.log('{{form.errors}}')
        Swal.fire({
            type: 'error',
            title: 'Oops...',
            text:   'Su nombre de usuario y contraseña no coinciden. Por favor, inténtalo de nuevo.',
            footer: '<a href="{% url "password_reset"%}" >¿Olvidaste tu contraseña?</a>'
    });
    $("body").removeClass("swal2-height-auto");

    </script>
{% endif %}

</html>

templates/main.html
{% load static %}
<!-- START PAGE SIDEBAR -->
<div class="page-sidebar">
    <!-- START X-NAVIGATION -->
    <ul class="x-navigation">
        <li class="xn-logo">
            <a href="{% url 'index'%}">Referir Paga</a>
            <a href="#" class="x-navigation-control" ><i class="fas fa-bars fa-2x"></i></a>
        </li>
        <li class="xn-profile">
            <a href="#" class="profile-mini">
                <img src="{% static 'assets/images/users/avatar.jpg' %}" alt="John Doe" />
            </a>
            <div class="profile">
                <div class="profile-image">
                    <img src="{% static 'assets/images/users/avatar.jpg' %}" alt="John Doe" />
                </div>
                <div class="profile-data">
                    <div class="profile-data-name">{{ user.first_name }}</div>
                    <div class="profile-data-title">{{user.username}}</div>
                </div>
                <div class="profile-controls">
<!--                    <a href="pages-profile.html" class="profile-control-left">-->
<!--                        <span class="fa fa-info"></span>-->
<!--                    </a>-->
<!--                    <a href="pages-messages.html" class="profile-control-right">-->
<!--                        <span class="fa fa-envelope"></span>-->
<!--                    </a>-->
                </div>
            </div>
        </li>
<!--        <li class="xn-title">Navigation</li>-->
<!--        <li class="">-->
<!--            <a href="{% url 'index'%}"><span class="fa fa-desktop"></span> <span class="xn-text">Dashboard</span></a>-->
<!--        </li>-->


{% if user.is_super_administrador == True and user.is_administrador == False %}
        <li class="xn-text">
            <a href="{% url 'clientes:cliente-index'%}">
                <span class="fa fa-users"></span> 
                <span class="xn-text">Clientes</span>
            </a>
        </li>
{% endif %}


{% if user.is_administrador  or user.is_administrador_punto  %}<!---or user.is_superuser NO APLICA--->
        {% if user.is_super_administrador == True and user.is_administrador == True %}
            <li class="xn-text">
                <a href="{% url 'logginas:reset-user'%}">
                    <span class="fa fa-eye-slash"></span>
                    <span class="xn-text">cerrar "ver como"</span>
                </a>
            </li>
        {% endif %}

        <li class="xn-text">
            <a href="{% url 'usuarios:usuario-index'%}">
                <span class="fa fa-users"></span>
                <span class="xn-text">Usuarios</span>
            </a>
        </li>

        <li class="xn-text">
            <a href="{% url 'gestores:cumpleanhos'%}">
                <span class="fa  fa-gift"></span> 
                <span class="xn-text">Cumpleaños</span>
            </a>
        </li>
{% endif %}

{% if user.is_administrador %} <!---or user.is_superuser NO APLICA--->
        <li>
            <a href="#"><span class="fa fa-cogs"></span> <span class="xn-text">Gestor De Puntos</span></a>
            <ul>
                <li>
                    <a href="{% url 'sedes:regional-index'%}">
                        <span class="fa fa-university"></span> 
                        <span class="xn-text">Gestión Regionales</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'sedes:pto-index'%}">
                        <span class="fa fa-map-marker"></span>
                        <span class="xn-text">Gestión Punto Operación</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'gestores:campania-index'%}">
                        <span class="fa fa-map-marker"></span>
                        <span class="xn-text">Gestión Campañias</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="xn-text">
            <a href="{% url 'gestores:enlace-index'%}">
                <span class="fa fa-random"></span>
                <span class="xn-text">Gestión de Enlaces</span>
            </a>
        </li>

        <li class="xn-text">
            <a href="{% url 'gestores:publicidad-index'%}">
                <span class="fa fa-paperclip"></span>
                <span class="xn-text">Gestión de Publicidad</span>
            </a>
        </li>

        <li class="xn-text">
            <a href="{% url 'gestores:servicio-index'%}">
                <span class="glyphicon glyphicon-hand-up"></span>
                <span class="xn-text">Gestión de Servicios</span>
            </a>
        </li>
        <li class="xn-text">
            <a href="{% url 'gestores:producto-index'%}">
                <span class="glyphicon glyphicon-briefcase"></span>
                <span class="xn-text">Gestión de Productos</span>
            </a>
        </li>


        <li>
            <a href="#">
                <span class="fa fa-file-download"></span>
                <span class="xn-text">Reportes</span>
            </a>
            <ul>
                {% if user.is_super_administrador %}
                <li>
                    <a href="{% url 'reportes:reportes-clientes'%}">
                        <span class="fas fa-file-alt"></span>
                        <span class="xn-text">Reporte Clientes</span>
                    </a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'reportes:reportes-enlace'%}">
                        <span class="fa fa-share-alt"></span> 
                        <span class="xn-text">Reporte Enlaces</span>
                    </a>
                </li>


                <li>
                    <a href="{% url 'reportes:reportes-publicidad'%}">
                        <span class="fa fa-cube"></span> 
                        <span class="xn-text">Reporte Publicidad</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'reportes:reportes-servicio'%}">
                        <span class="fa fa-briefcase"></span> 
                        <span class="xn-text">Reporte Servicios</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'reportes:reportes-regionales-pto'%}">
                        <span class="fa fa-hotel"></span> 
                        <span class="xn-text">Reporte Regionales Punto Operacion</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'reportes:reportes-usuarios'%}">
                        <span class="fa fa-file-excel"></span> 
                        <span class="xn-text">Reporte Usuarios</span>
                    </a>
                </li>
            </ul>
        </li>

{% endif %}


<!--



        <li class="xn-openable">
            <a href="#"><span class="fa fa-file-text-o"></span> <span class="xn-text">Layouts</span></a>
            <ul>
                <li><a href="layout-boxed.html">Boxed</a></li>
                <li><a href="layout-nav-toggled.html">Navigation Toggled</a></li>
                <li><a href="layout-nav-top.html">Navigation Top</a></li>
                <li><a href="layout-nav-right.html">Navigation Right</a></li>
                <li><a href="layout-nav-top-fixed.html">Top Navigation Fixed</a></li>
                <li><a href="layout-nav-custom.html">Custom Navigation</a></li>
                <li><a href="layout-frame-left.html">Frame Left Column</a></li>
                <li><a href="layout-frame-right.html">Frame Right Column</a></li>
                <li><a href="layout-search-left.html">Search Left Side</a></li>
                <li><a href="blank.html">Blank Page</a></li>
            </ul>
        </li>
        <li class="xn-title">Components</li>
        <li class="xn-openable">
            <a href="#"><span class="fa fa-cogs"></span> <span class="xn-text">UI Kits</span></a>
            <ul>
                <li><a href="ui-widgets.html"><span class="fa fa-heart"></span> Widgets</a></li>
                <li><a href="ui-elements.html"><span class="fa fa-cogs"></span> Elements</a></li>
                <li><a href="ui-buttons.html"><span class="fa fa-square-o"></span> Buttons</a></li>
                <li><a href="ui-panels.html"><span class="fa fa-pencil-square-o"></span> Panels</a></li>
                <li><a href="ui-icons.html"><span class="fa fa-magic"></span> Icons</a>
                    <div class="informer informer-warning">+679</div>
                </li>
                <li><a href="ui-typography.html"><span class="fa fa-pencil"></span> Typography</a></li>
                <li><a href="ui-portlet.html"><span class="fa fa-th"></span> Portlet</a></li>
                <li><a href="ui-sliders.html"><span class="fa fa-arrows-h"></span> Sliders</a></li>
                <li><a href="ui-alerts-popups.html"><span class="fa fa-warning"></span> Alerts & Popups</a></li>
                <li><a href="ui-lists.html"><span class="fa fa-list-ul"></span> Lists</a></li>
                <li><a href="ui-tour.html"><span class="fa fa-random"></span> Tour</a></li>
            </ul>
        </li>
        <li class="xn-openable">
            <a href="#"><span class="fa fa-pencil"></span> <span class="xn-text">Forms</span></a>
            <ul>
                <li>
                    <a href="form-layouts-two-column.html"><span class="fa fa-tasks"></span> Form Layouts</a>
                    <div class="informer informer-danger">New</div>
                    <ul>
                        <li><a href="form-layouts-one-column.html"><span class="fa fa-align-justify"></span> One Column</a></li>
                        <li><a href="form-layouts-two-column.html"><span class="fa fa-th-large"></span> Two Column</a></li>
                        <li><a href="form-layouts-tabbed.html"><span class="fa fa-table"></span> Tabbed</a></li>
                        <li><a href="form-layouts-separated.html"><span class="fa fa-th-list"></span> Separated Rows</a></li>
                    </ul>
                </li>
                <li><a href="form-elements.html"><span class="fa fa-file-text-o"></span> Elements</a></li>
                <li><a href="form-validation.html"><span class="fa fa-list-alt"></span> Validation</a></li>
                <li><a href="form-wizards.html"><span class="fa fa-arrow-right"></span> Wizards</a></li>
                <li><a href="form-editors.html"><span class="fa fa-text-width"></span> WYSIWYG Editors</a></li>
                <li><a href="form-file-handling.html"><span class="fa fa-floppy-o"></span> File Handling</a></li>
            </ul>
        </li>
        <li class="xn-openable">
            <a href="tables.html"><span class="fa fa-table"></span> <span class="xn-text">Tables</span></a>
            <ul>
                <li><a href="table-basic.html"><span class="fa fa-align-justify"></span> Basic</a></li>
                <li><a href="table-datatables.html"><span class="fa fa-sort-alpha-desc"></span> Data Tables</a></li>
                <li><a href="table-export.html"><span class="fa fa-download"></span> Export Tables</a></li>
            </ul>
        </li>
        <li class="xn-openable">
            <a href="#"><span class="fa fa-bar-chart-o"></span> <span class="xn-text">Charts</span></a>
            <ul>
                <li><a href="charts-morris.html"><span class="xn-text">Morris</span></a></li>
                <li><a href="charts-nvd3.html"><span class="xn-text">NVD3</span></a></li>
                <li><a href="charts-rickshaw.html"><span class="xn-text">Rickshaw</span></a></li>
                <li><a href="charts-other.html"><span class="xn-text">Other</span></a></li>
            </ul>
        </li>
        <li>
            <a href="maps.html"><span class="fa fa-map-marker"></span> <span class="xn-text">Maps</span></a>
        </li>
        <li class="xn-openable">
            <a href="#"><span class="fa fa-sitemap"></span> <span class="xn-text">Navigation Levels</span></a>
            <ul>
                <li class="xn-openable">
                    <a href="#">Second Level</a>
                    <ul>
                        <li class="xn-openable">
                            <a href="#">Third Level</a>
                            <ul>
                                <li class="xn-openable">
                                    <a href="#">Fourth Level</a>
                                    <ul>
                                        <li><a href="#">Fifth Level</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>

-->
    
    </ul>
    <!-- END X-NAVIGATION -->
</div>
<!-- END PAGE SIDEBAR -->
<!-- PAGE CONTENT -->

templates/scripts.html
{% load static %}
<!-- START SCRIPTS -->
<!-- START PLUGINS -->
<script type="text/javascript" src="{% static 'js/plugins/jquery/jquery.min.js' %}"></script>



<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet"/>






<script type="text/javascript" src="{% static 'js/plugins/jquery/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- END PLUGINS -->
<!-- START THIS PAGE PLUGINS-->
<script type='text/javascript' src="{% static 'js/plugins/icheck/icheck.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js' %}"></script>
<!--script type="text/javascript" src="{% static 'js/plugins/scrolltotop/scrolltopcontrol.js' %}"></script-->
<script type="text/javascript" src="{% static 'js/plugins/morris/raphael-min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/morris/morris.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/rickshaw/d3.v3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/rickshaw/rickshaw.min.js' %}"></script>
<script type='text/javascript' src="{% static 'js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script type='text/javascript' src="{% static 'js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script type='text/javascript' src="{% static 'js/plugins/bootstrap/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/owl/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- END THIS PAGE PLUGINS-->
<!-- START TEMPLATE -->
<script type="text/javascript" src="{% static 'js/settings.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins.js' %}"></script>
<script type="text/javascript" src="{% static 'js/actions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/demo_dashboard.js' %}"></script>
<!-- END TEMPLATE -->
<!-- END SCRIPTS -->
<!-- start  sweetalert-->
<script type="text/javascript" src="{% static 'js/plugins/sweetalert2.8/sweetalert.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins/toastr/toastr.js' %}"></script>
<script type="text/javascript" src="{% static 'js/global.js' %}"></script>

<!-- END sweetalert -->

templates/scriptsstart.html
{% load static %}
<!-- START SCRIPTS -->
<!-- START PLUGINS -->
<script type="text/javascript" src="{% static 'js/gobal js inicial.js' %}"></script>